# Generated by Django 4.1.2 on 2022-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app16', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Model', models.CharField(max_length=20)),
                ('Engine', models.CharField(max_length=8)),
            ],
        ),
    ]
