# Generated by Django 4.1.2 on 2022-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app16', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Engine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='Model',
            field=models.CharField(max_length=40),
        ),
    ]
